### ISSUE TITLE
Add Category/Collection/Folder support

### ISSUE THREAD

**Issue by jbrodriguez** [wincent/corpus#55]
To organize notes,
1st column = category
2nd column = note title
3rd column = note content

**Comment by wincent** [comment]
Thanks for the suggestion, @jbrodriguez. I'd be interested in hearing more about how you'd want this to work, especially in relation to a couple of other features/ideas:

See #48, which is about teaching Corpus to read/manage notes in multiple folders. My main use case for that would be separating work and personal notes (I can sync my personal notes to Dropbox, but I can't sync my work notes).

For categories, I just use tags defined in the Markdown header:

```
---
tags: foo bar baz
---

Rest of note goes here.
```

To see all the notes with a particular tag, I either search for `#foo` (`#foo #bar`) etc, or click on one of the tag pills in the notes list (I'll add Command-clicking as well I think to select multiple tags).

**Comment by jbrodriguez** [comment]
Ok, I hadn't noticed the tags.

I think that would suit me.

Thanks !
