### ISSUE TITLE
Sort by last modified

### ISSUE THREAD

**Issue by mikepqr** [wincent/corpus#74]
Should Corpus's file list sort by modification time (most recent first) rather than lexographical? This behavior would match nvalt and friends and I find it useful.

**Comment by wincent** [comment]
That's a good idea. Back when it was written in Vimscript I wouldn't have considered this because it would have been too slow, but now it is ported to Lua it's quite likely that it can be done with acceptable performance.

**Comment by mikepqr** [comment]
Just thinking about this issue because it's tax season here. When I search for `taxes 2020` these are my results, i.e. the thing I want is last.

```
taxes 2018
taxes 2019
taxes 2020
```

Both this issue and #47 (IIUC correctly) would help with this issue.

**Comment by mikepqr** [comment]
Thanks @wincent!
