### ISSUE TITLE
Preview pane empty

### ISSUE THREAD

**Issue by williamsmj** [wincent/corpus#75]
My preview pane is empty (i.e. the markdown files contain text, but the preview on the right hand side is blank). I'm using NVIM v0.5.0-d8c69ad (i.e. HEAD at the time of writing). Are there any additional dependencies or configuration steps I might be missing for working preview?

**Comment by wincent** [comment]
I haven't seen this. Can you provide more details of your set-up? What is your config, where are the files on the disk, are there any symlinks or other oddities like network mounted drives involved etc?

**Comment by williamsmj** [comment]
By bisecting my config I figured out the problem: my colorscheme, [iceberg.vim](https://github.com/cocopon/iceberg.vim/blob/master/colors/iceberg.vim).

Corpus renders the preview as `VertSplit`, and iceberg.vim has the VertSplit background and foreground as the same color. Result: invisible previews!

So: problem solved from my POV. I have `autocmd ColorScheme * highlight! link VertSplit Normal` in my vimrc for now, and I'll keep an eye out for the [change mentioned here](https://github.com/wincent/corpus/blob/ac5dc090626af934884e43dd1a39df5eaa01de0a/lua/corpus/init.lua#L418).

**Comment by wincent** [comment]
I believe https://github.com/wincent/corpus/commit/9d5de77477a913a916826167f8a20cabe55667c2 should do the trick.

**Comment by williamsmj** [comment]
Perfect, thanks! 

(Just a nit, but I'd lean toward a different default. VertSplit is decoration so colorschemes are not designed with the expectation it it will be used to render text. It seems more likely than almost any other syntax group to be set up with very low or no contrast between fg and bg.)

**Comment by wincent** [comment]
> Just a nit, but I'd lean toward a different default. VertSplit is decoration so colorschemes are not designed with the expectation it it will be used to render text. It seems more likely than almost any other syntax group to be set up with very low or no contrast between fg and bg.

Just got an email from somebody wondering why they can't see the preview, so you may be right about that. I'm going to see if I can find a different default that looks reasonable out-of-the-box.
