### ISSUE TITLE
CorpusSort='stat' fails on neovim 0.9.1

### ISSUE THREAD

**Issue by mikepqr** [wincent/corpus#85]
Looks like https://github.com/wincent/corpus/commit/1ad831221320def4c86a6a2edb86057f8bc34f65 depends on https://github.com/neovim/neovim/pull/22846/ when it calls `vim.uv.fs_stat`. At the time of writing, `lib.uv` requires an unreleased build of neovim, and is not available in the latest official release, which is 0.9.1.

The README warns that "Corpus requires a recent version of Neovim", so I hesitate to call this an issue, and I will absolutely not be offended if you close this immediately, but it's an easy fix if you choose to maintain support for the latest official neovim release.

**Comment by wincent** [comment]
Thanks for the heads up. I agree that the compatibility fallback is simple enough to implement so I'll do that.
